# flake8: noqa

"""
    Bundeshaushalt API

    Mit unserem Tool „Bundeshaushalt digital“ können Sie sich eine visualisierte Darstellung der Haushaltsdaten der letzten Jahre anzeigen lassen. Sie können sowohl Ausgaben und Einnahmen als auch Soll- und Ist-Werte abrufen und mithilfe des Jahresvergleichs gegenüberstellen. Zudem steht Ihnen eine Vielzahl weiterer Filteroptionen zur Verfügung.<br>  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: anetz@gmx.net
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from deutschland.bundeshaushalt.api_client import ApiClient

# import Configuration
from deutschland.bundeshaushalt.configuration import Configuration

# import exceptions
from deutschland.bundeshaushalt.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)
