"""
    Bundeshaushalt API

    Mit unserem Tool „Bundeshaushalt digital“ können Sie sich eine visualisierte Darstellung der Haushaltsdaten der letzten Jahre anzeigen lassen. Sie können sowohl Ausgaben und Einnahmen als auch Soll- und Ist-Werte abrufen und mithilfe des Jahresvergleichs gegenüberstellen. Zudem steht Ihnen eine Vielzahl weiterer Filteroptionen zur Verfügung.<br>  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: anetz@gmx.net
    Generated by: https://openapi-generator.tech
"""

import unittest

from deutschland.bundeshaushalt.api.budget_data_api import BudgetDataApi  # noqa: E501

from deutschland import bundeshaushalt


class TestBudgetDataApi(unittest.TestCase):
    """BudgetDataApi unit test stubs"""

    def setUp(self):
        self.api = BudgetDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_budget_data(self):
        """Test case for budget_data

        Anfrage von Budgetdaten des Bundeshaushalts.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
